# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f8c55bbe4dce9a9cb56a3eec217f24838f745f784aefabdaf85d926df9a22ef8352163023db7b3c5d8dc8fa8b2d2feec841a23f195c159b1c098ade41c4c225

test:
  secret_key_base: fe0c8b1648b1dd65a09abbeaa7c49a0c9ad5175f2a7ce16ab236382a1309f0c3293b0415309a0c8231abb671e06989c4a4ada21f3c1de8848faf4acc0099d202

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
