# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46de46860c8a3b497ff755abfae05635f0c9818784061ee8e30f98ccbeeae2c5def03f0ef99f547721c8d781c4f2460dd863a8b5085753eadf49382aa875c456

test:
  secret_key_base: 6b75f9554f04e2cce3a36872384be73b446c64ada22b2f3a79e9ffd4d3d6f325b966154516107ce3d230285b3f3f9e472d39b91c04c865141b98c8e3728bec0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
