# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cdcbcbd903574c5fcccda123dfc476c119433b5102981f49b8991c426a8025fc339d5f8b0ae82860efaa60b2e6a7ca2f94afcab8773057f2a3b9610b1e0dffb

test:
  secret_key_base: 77b2e61891391e457ac5c56ffd3d8455799c450db4e87e8c250b063799a72f8bf0f8f1858f59fa0022d0ef5e2cc951b9809776a1d6efb7cf911157cb34eac431

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
